var hobbies=new Array("travell","sleeping","cricket")
console.log(hobbies)
var sports=new Array("football","cricket","hockey")
console.log(sports)
var subject=new Array("phy","che","math")
console.log(hobbies)
var animal=new Array("cow","tiger","beer")
console.log(hobbies)
var mixArray=new Array("travell",10.5,10)
console.log(mixArray)
console.log("array with out new keyword========================================")
var fruits=[
    "apple","plum","pinaple","blackberry"
];
console.log(fruits)
var sports=[
    "football","cricket","hockey"
];
console.log(sports)
var subject=[
    "math","hindi","english"
];
console.log(subject)
var country=[
    "india","germany","usa"
];
console.log(country)
var hobbies=[
    "travell","cricket","movie"
];
console.log(hobbies)
console.log("print the value of array of loop through*******************************")
var number=[1,2,3,4,5,6,7,8,9,10,25,36,65,89,57,56,87,4,2];
for(var i=0;i<number.length;i++)
{
    console.log("number is "+number[i])
}
console.log("array value by for of loop======================")
for(var ary in number)
{
    console.log("the number of array "+ary)
}





